version: '3.8'
services:

  postgres:
    image: postgres:13.5
    restart: always
    environment:
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  tracing:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

volumes:
  postgres:
